services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  db_data: